language: python
python:
- '3.7'

install: pipenv install
script: pytest -v -s --disable-warnings

beta:
  provider: pypi
  server: https://testpypi.python.org/pypi
  user: zabana
  password:
    secure: njYB2nW2nT9j7FvCai2ijQiTMNqEezMLytts5Rg3x1l9ZaKaJXAnSDvSdxfU8tmOVwvHINylidZdD+sVaPxx7JYO9GTgcsosmrAzV0gjZCubG0T1DzBJYLCk8ipZEDSXS0ddmh4WdbiT5oNL4Jq3fVic459nT0SvBG007A1+2/Q4uFSYsDjcV5OEqpbYmNZFiB8j5HNB5BDOUqd/XuZHZeOv/svppvBHoGxWIiJ6B+ReOqE8bCjDeO/QLj+Dh/0QCJdKKDJr5NLzeDDhHZgpmO2kfJ8rRvZ8HFvbMaRKhQXaPlq0RqAbzsroS3LypWStpAY4emEUZ8tdGQk+DgQMdqpI3eL6JEqfmZKKojVG31gFeo9L153koZPYwlmsNMwdCW5TOLCJ5iQ3jNcG1qctbbPFPOu1q8wpMgD36daXcDiyU68xMrtq3cosoqSwmNZz7ModGmTV+2o/ERbbKPumkPwc37xTZw+8fsIiHpotvPFA+M8iqNLMlWHjD3SD04yfCyq+QNNhJGeAeJWapxpd66AuP+874713F8EbahU172bp/wxf5Kwa1Q7zGRWYfvHNRj/oM8NxH6tU9ggPZlrnxg8LFmpNeo+IQc9//7yg8MVrA7VXuUhcT/WOEGWZMntfrYbl9zwsFP88DFQ5M6P9GU8NvDWOrhR8xcpnakYsGxY=
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    branch: master

release:
  provider: pypi
  user: zabana
  password:
    secure: jcpIycw6VNAxTnP5bHnbDDb+WQq3e4x65rLN6inBBXgoFSC2x56HozsSQD5fe4aDgNIsZ9rIYDQMmG3kEcn9yw5XNznjITPJNK8OtckIrXXaFS1BsAsSZjiFI+yeoS5pmEpkpxXZgvsq8ghB2KcoKCWcuTLXXLWB/a7Up/zMjYbjmUHoqEaX4tG4tHjXZ+6uAbpg4Ulww/47pVPoOsm23xplpxP4uJ4vi7U6HdKSWrW7nusoN/t8D6fQPyIZTA7hLqT41ZG1JZIRpHTmZ7UrqP5o0fYJzWSw5AP0jnMJAZJUEroVPykvYVGwvglFF4V6gcRuM8TY+VpD7bWiuGg+tc1h7Nw9HiyLHMgPWC1XwI7Mou8G0RqtLLBN/X5SBRzx/5h8UOPpTiXsoLHWJkq9cfUtG+BCzTa1DVnXEPAON0l+OntUCJNy2fZr9G2vXCvIANpZ4YUcL+iK//XcH9lgCc2/uTXZdpmbc8q4BVpyS01QzCDVRizLAbOAnE6ecKYzIxdcuZFHRAnGEhnNAHwSGbKTIdqru97q+d9N0HGBsQp5awSSsdw6LxriJ97q+sJGB5i5aazdyASnr1gWKJAN3BxARwBc6rNAqY2dSQ9s2rhfo2u+GMsos8IEb2wapxcegaUNphHCYpNCw3VCsmgSFRlvSDQqIWal9LMZBHvOCXc=
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    branch: production
